AllCops:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/helpers.rb'
Metrics/MethodLength:
  Exclude:
    - 'spec/helpers.rb'
Metrics/ModuleLength:
  Exclude:
    - 'spec/helpers.rb'
